/** 地图「地名」层：tarkov.dev maps.json 的 label.text 是英文/俄文，站点 zh 文案也不覆盖这些点。 */

const TARKOV_MAP_LABEL_ZH: Record<string, string> = {
  "Primorsky Ave.": "滨海大道",
  "Kilmov St.": "克利莫夫大街",
  "Nikitskaya St.": "尼基茨卡娅大街",
  "Verhnyaya St.": "上街",
  "Malevecha St.": "马列维奇大街",
  "Chekannaya St.": "切坎纳亚大街",
  "Nizhnyaya St.": "下街",
  "Razvedchikov St.": "侦察兵大街",
  "Zmejskij Alley": "蛇巷",
  "Kamchatskaya St.": "堪察加大街",
  "Kilmov Shopping Mall": "克利莫夫商场",
  Beluga: "白鲸",
  "Cardinal Apartments": "红衣主教公寓",
  Construction: "工地",
  Lexos: "莱克索斯",
  "Sparja Grocery": "斯帕加超市",
  Cinema: "电影院",
  Shestyorochka: "六点超市",
  "Pinewood Hotel": "松木酒店",
  "Teppakot / Koener": "特帕科特 / 科纳",
  Concordia: "康科迪亚",
  "Cardinal Bank": "红衣主教银行",
  "LERM Expo": "LERM 会展",
  "Sparja Express": "斯帕加便利店",
  "Burger Spot": "汉堡点",
  "Post Office": "邮局",
  "Pharmacy 1": "药店 1",
  Office: "办公室",
  "Corner Restaurant": "街角餐厅",
  "Pharmacy 2": "药店 2",
  "Pharmacy 3": "药店 3",
  Tarbank: "塔尔银行",
  School: "学校",
  "Vet Clinic": "兽医诊所",
  Hive: "蜂巢",
  "Family Market": "家庭超市",
  "Marked Hotel": "标记酒店",
  "South Hotel": "南酒店",
  "Abandon Factory": "废弃工厂",
  Diner: "餐厅",
  "Primorskij 49": "滨海 49 号",
  "Prestigio Cafe": "声望咖啡馆",
  "Bilbo Coffee": "比尔博咖啡",
  TerraGroup: "TerraGroup",
  Skyside: "天际",
  Fusion: "融合",
  Empire: "帝国",
  "Capital Insight": "资本洞察",
  Nakatani: "中谷",
  "Elemental Global": "元素全球",
  Oasis: "绿洲",
  "ASAP Winery": "ASAP 酒庄",
  "GAGRIN Hotel": "加加林酒店",
  "M Showroom": "M 展厅",
  "Science Office": "科学办公室",
  "Big Red": "大红房",
  Dorms: "宿舍",
  "New Gas": "新加油站",
  "New Gas Station": "新加油站",
  "Old Gas": "老加油站",
  "Old Gas Station": "老加油站",
  Fortress: "要塞",
  Stronghold: "要塞",
  Crackhouse: "裂纹房",
  "Streamer House": "主播房",
  "Main Bridge": "主桥",
  "Sniper Hill": "狙击坡",
  Storage: "仓储区",
  "Trailer Park": "拖车场",
  "Junk Bridge": "废车桥",
  "Repair Shop": "修理店",
  "Sniper Ridge": "狙击岭",
  "Old Construction": "旧工地",
  Skeleton: "骨架楼",
  "Warehouse 3": "3 号仓库",
  Depot: "货场",
  "Warehouse 7": "7 号仓库",
  "Military Checkpoint": "军事检查站",
  "Bus Station": "公交站",
  "Warehouse 4": "4 号仓库",
  "Powerline Tower": "电塔",
  "Warehouse 17": "17 号仓库",
  "Office Building": "办公楼",
  "Main Office": "主办公区",
  "Breach Room": "破拆房间",
  "Locked Office": "上锁办公室",
  "North Stairs": "北楼梯",
  "South Stairs": "南楼梯",
  "Sky Bridge": "天桥",
  Connector: "连接廊",
  "Locker Rooms": "更衣室",
  Sinks: "水槽",
  Hole: "破洞",
  Platform: "平台",
  Servers: "服务器",
  "Med Tent": "医疗帐篷",
  Silos: "筒仓",
  "Heli Crash": "坠机点",
  Pit: "深坑",
  "Underground Stash": "地下藏匿点",
  "Scav Bunker": "Scav 地堡",
  "Blue Containers": "蓝色集装箱",
  "Wood Room": "木屋",
  "Glass Hall": "玻璃厅",
  Boilers: "锅炉",
  "Pumping Station": "泵站",
  "East Halls": "东厅",
  Forklifts: "叉车区",
  Rafters: "屋架",
  "Power Station": "发电站",
  "Go Kart": "卡丁车场",
  "Four Camp": "四人营地",
  "Cargo Containers": "集装箱",
  "Wall Break": "破墙",
  Ramps: "坡道",
  "Oli Tower": "OLI 塔",
  "Idea Tower": "IDEA 塔",
  "Scav Camp": "Scav 营地",
  "Highway Construction": "公路工地",
  "Garage A": "车库 A",
  "Garage B": "车库 B",
  "Garage C": "车库 C",
  "Garage D": "车库 D",
  IDEA: "IDEA",
  Goshan: "好圣",
  OLI: "OLI",
  Nortex: "诺泰克斯",
  TRend: "TRend",
  Mode7: "Mode7",
  TTS: "TTS",
  "Book Store": "书店",
  "Dino Clothes": "恐龙服装",
  EMERCOM: "应急部",
  Kostin: "科斯廷",
  Bizarro: "奇异",
  Spiel: "斯皮尔",
  Voyage: "远航",
  Viking: "维京",
  Mantis: "螳螂",
  German: "德式",
  "The National": "国家",
  Brutal: "Brutal",
  Kiba: "奇巴",
  "Pretty Lights": "彩灯",
  Telespot: "电视角",
  Revis: "Revis",
  ADIK: "ADIK",
  Generic: "通用店",
  "Top Brand": "顶级品牌",
  Sports: "体育用品",
  Yushka: "尤什卡",
  Rasmussen: "拉斯穆森",
  Avokado: "牛油果",
  "Boots 4 Life": "终身靴店",
  Texho: "特克索",
  Dom: "家",
  "Father & Sons": "父与子",
  Tarkovstar: "塔科夫之星",
  Eastland: "东地",
  Arena: "竞技场",
  ТАРЗДРАВ: "塔尔健康",
  "МЕБЕЛЬ МК": "MK 家具",
  Intourist: "因图里斯特",
  FCK: "FCK",
  McDaniels: "麦丹尼尔",
  Tarducks: "塔达克",
  "Coffee Joy": "乐咖",
  "Jacob & Jacob": "雅各布",
  ПУШКИН: "普希金",
  "Sushi Huyushi": "寿司",
  Underway: "通道",
  "Burger House": "汉堡屋",
  "Philly Cute": "费城可爱",
  Shiccos: "希科",
  "МУЗЕЙ ИСТОРИИ": "历史博物馆",
  Papillon: "蝴蝶",
  "ЗАКРЫТО НА РЕМОНТ": "维修关闭",
  "НА-СВЯЗИ": "保持联系",
  "СКОРО ОТКРЫТИЕ": "即将开业",
  Figaro: "费加罗",
  АПТЕКА: "药店",
  SARA: "SARA",
  "Urban Clothes": "都市服装",
  TECHLIGHT: "科技灯具",
  "Fashion Store": "时装店",
  Parking: "停车场",
  "Vestibules #1": "门厅 1",
  "Vestibules #2": "门厅 2",
  "Main Working Area": "主作业区",
  "Negotiation Room": "谈判室",
  "Infirmary Lvl 1": "医务室 1 层",
  "Test Room": "测试室",
  "Server Room": "服务器室",
  "Warehouse Tunnels": "仓库隧道",
  Warehouse: "仓库",
  "Warehouse Gate": "仓库大门",
  "Lecture Hall": "报告厅",
  "Recreation Area": "休息区",
  Gym: "健身房",
  "Men's Locker Room": "男更衣室",
  "Women's Locker Room": "女更衣室",
  "Boiler Room": "锅炉房",
  "Security Barracks": "安保营房",
  Reception: "前台",
  "Administrative Office": "行政办公室",
  "Security Office": "安保办公室",
  "Security #1": "安保 1",
  "Security #2": "安保 2",
  "Conference Room": "会议室",
  Cafeteria: "食堂",
  "Offices #1": "办公室 1",
  "Offices #2": "办公室 2",
  "Infirmary Lvl 2": "医务室 2 层",
  "Sterile Laboratory": "无菌实验室",
  "Control Room": "控制室",
  "Corridor To Building #2": "通往 2 号楼走廊",
  "Train Yard": "列车场",
  "Drug Lab": "制药实验室",
  "Water Treatment": "水处理",
  "Plant 1": "厂房 1",
  "Plant 2": "厂房 2",
  "Plant 3": "厂房 3",
  Pipes: "管道",
  "Gunner Nest": "机枪位",
  Island: "小岛",
  Cabins: "小屋",
  Cottages: "别墅",
  Convenience: "便利店",
  "Red Brick": "红砖房",
  Hillside: "山坡",
  Boathouses: "船屋",
  "Dead Tree": "枯树",
  "Pikes Peak Resort": "派克峰度假村",
  "Grand Chalet": "大木屋",
  "Tennis Court": "网球场",
  "Lightkeeper Island": "灯塔商人之岛",
  "Crash Site": "坠机点",
  "K Buildings": "K 楼",
  "White Queen": "白后",
  "White Pawn": "白兵",
  "Black Bishop": "黑象",
  "White Bishop": "白象",
  "White King": "白王",
  "Black Knight": "黑马",
  "White Knight": "白马",
  "White Rook": "白车",
  "Train Station": "火车站",
  "Black Pawn": "黑兵",
  Barracks: "营房",
  "E1 Bunkers": "E1 地堡",
  "E2 Bunkers": "E2 地堡",
  "д - Warehouse Bunkers": "仓库地堡",
  Garage: "车库",
  Mechanic: "技师",
  "Gas Station": "加油站",
  "Shipping Yard": "船运货场",
  K1: "K1",
  K2: "K2",
  K3: "K3",
  K4: "K4",
  K5: "K5",
  K6: "K6",
  Dome: "穹顶",
  Tarmac: "停机坪",
  Resort: "度假村",
  "Weather Station": "气象站",
  "Radio Tower": "无线电塔",
  Swamp: "沼泽",
  Village: "村庄",
  "Tank Bridge": "坦克桥",
  Pier: "码头",
  "Scav Island": "Scav 岛",
  "Bus Stop": "公交站",
  Bunker: "地堡",
  Crane: "吊车",
  "Scav Farm": "Scav 农场",
  "West Wing": "西翼",
  "East Wing": "东翼",
  Admin: "行政楼",
  Sawmill: "锯木厂",
  "Scav Town": "Scav 镇",
  "Old Sawmill": "旧锯木厂",
  "Cultist Village": "邪教村",
  "USEC Camp": "USEC 营地",
  "Military Camp": "军营",
  Ponds: "池塘",
  Checkpoint: "检查站",
  Shack: "小屋",
  Lumber: "木材场",
  "Jaeger's Camp": "猎人营地",
  "Sniper Rock": "狙击石",
  Convoy: "车队",
};

export function tarkovMapLabel(text: string): string {
  const key = (text || "").trim();
  if (!key) return "";
  return TARKOV_MAP_LABEL_ZH[key] || key;
}

export function hasTarkovMapLabel(text: string): boolean {
  return Object.prototype.hasOwnProperty.call(
    TARKOV_MAP_LABEL_ZH,
    (text || "").trim(),
  );
}
